#############################################################################
# Makefile for building: qt-ios-app-test.app/Contents/MacOS/qt-ios-app-test
# Generated by qmake (3.0) (Qt 5.2.0)
# Project:  qt-ios-app-test.pro
# Template: app
# Command: /usr/bin/ios_qmake -spec macx-xcode -o qt-ios-app-test.xcodeproj/project.pbxproj qt-ios-app-test.pro
#############################################################################

MAKEFILE      = project.pbxproj

QMAKE    = /usr/bin/ios_qmake
qt-ios-app-test.xcodeproj/project.pbxproj: qt-ios-app-test.pro ../../../Qt5.2.0/5.2.0/ios/mkspecs/macx-ios-clang/qmake.conf ../../../Qt5.2.0/5.2.0/ios/mkspecs/features/spec_pre.prf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/qdevice.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/features/device_config.prf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/common/shell-unix.conf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/common/unix.conf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/common/mac.conf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/common/ios.conf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/common/gcc-base.conf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/common/gcc-base-mac.conf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/common/clang.conf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/common/clang-mac.conf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/common/ios/clang.conf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/common/ios/qmake.conf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/qconfig.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_cocoaprintersupport.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qavfcamera.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qico.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qios.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qminimal.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qmldbg_qtquick2.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qmldbg_tcp_qtdeclarative.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qmng.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qsvg.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qtaccessiblequick.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qtaccessiblewidgets.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qtga.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qtiff.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qwbmp.pri \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/features/qt_functions.prf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/features/qt_config.prf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/macx-ios-clang/features/qt_config.prf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/macx-ios-clang/qmake.conf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/macx-xcode/qmake.conf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/features/spec_post.prf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/features/default_pre.prf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/features/mac/default_pre.prf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/macx-ios-clang/features/default_pre.prf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/features/resolve_config.prf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/features/default_post.prf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/features/mac/sdk.prf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/features/mac/default_post.prf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/macx-ios-clang/features/default_post.prf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/features/mac/objective_c.prf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/features/warn_on.prf \
		../../../Qt5.2.0/5.2.0/ios/plugins/platforms/libqios_debug.prl \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/features/qt.prf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/macx-ios-clang/features/qt.prf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/features/resources.prf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/features/moc.prf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/features/unix/opengl.prf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/features/uic.prf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/features/unix/thread.prf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/features/mac/rez.prf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/features/testcase_targets.prf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/features/exceptions.prf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/features/yacc.prf \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/features/lex.prf \
		qt-ios-app-test.pro \
		../../../Qt5.2.0/5.2.0/ios/mkspecs/macx-ios-clang/Default-568h@2x.png \
		/Users/chenhsueh-min/Qt5.2.0/5.2.0/ios/plugins/platforms/libqios_debug.prl \
		/Users/chenhsueh-min/Qt5.2.0/5.2.0/ios/lib/libQt5PlatformSupport_debug.prl \
		/Users/chenhsueh-min/Qt5.2.0/5.2.0/ios/lib/libQt5Gui_debug.prl \
		/Users/chenhsueh-min/Qt5.2.0/5.2.0/ios/lib/libQt5Core_debug.prl \
		/Users/chenhsueh-min/Qt5.2.0/5.2.0/ios/lib/libQt5Widgets_debug.prl
	$(QMAKE) -spec macx-xcode -o qt-ios-app-test.xcodeproj/project.pbxproj qt-ios-app-test.pro
../../../Qt5.2.0/5.2.0/ios/mkspecs/features/spec_pre.prf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/qdevice.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/features/device_config.prf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/common/shell-unix.conf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/common/unix.conf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/common/mac.conf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/common/ios.conf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/common/gcc-base.conf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/common/gcc-base-mac.conf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/common/clang.conf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/common/clang-mac.conf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/common/ios/clang.conf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/common/ios/qmake.conf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/qconfig.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_core.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_declarative.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_declarative_private.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_gui.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_network.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_qml.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_quick.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_script.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_sql.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_svg.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_xml.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_cocoaprintersupport.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qavfcamera.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qico.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qios.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qminimal.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qmldbg_qtquick2.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qmldbg_tcp_qtdeclarative.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qmng.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qoffscreen.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qsqlite.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qsvg.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qsvgicon.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qtaccessiblequick.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qtaccessiblewidgets.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qtga.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qtiff.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/modules/qt_plugin_qwbmp.pri:
../../../Qt5.2.0/5.2.0/ios/mkspecs/features/qt_functions.prf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/features/qt_config.prf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/macx-ios-clang/features/qt_config.prf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/macx-ios-clang/qmake.conf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/macx-xcode/qmake.conf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/features/spec_post.prf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/features/exclusive_builds.prf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/features/default_pre.prf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/features/mac/default_pre.prf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/macx-ios-clang/features/default_pre.prf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/features/resolve_config.prf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/features/default_post.prf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/features/mac/sdk.prf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/features/mac/default_post.prf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/macx-ios-clang/features/default_post.prf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/features/mac/objective_c.prf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/features/warn_on.prf:
../../../Qt5.2.0/5.2.0/ios/plugins/platforms/libqios_debug.prl:
../../../Qt5.2.0/5.2.0/ios/mkspecs/features/qt.prf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/macx-ios-clang/features/qt.prf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/features/resources.prf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/features/moc.prf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/features/unix/opengl.prf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/features/uic.prf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/features/unix/thread.prf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/features/mac/rez.prf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/features/testcase_targets.prf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/features/exceptions.prf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/features/yacc.prf:
../../../Qt5.2.0/5.2.0/ios/mkspecs/features/lex.prf:
qt-ios-app-test.pro:
../../../Qt5.2.0/5.2.0/ios/mkspecs/macx-ios-clang/Default-568h@2x.png:
/Users/chenhsueh-min/Qt5.2.0/5.2.0/ios/plugins/platforms/libqios_debug.prl:
/Users/chenhsueh-min/Qt5.2.0/5.2.0/ios/lib/libQt5PlatformSupport_debug.prl:
/Users/chenhsueh-min/Qt5.2.0/5.2.0/ios/lib/libQt5Gui_debug.prl:
/Users/chenhsueh-min/Qt5.2.0/5.2.0/ios/lib/libQt5Core_debug.prl:
/Users/chenhsueh-min/Qt5.2.0/5.2.0/ios/lib/libQt5Widgets_debug.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-xcode -o qt-ios-app-test.xcodeproj/project.pbxproj qt-ios-app-test.pro

qmake_all: FORCE

