#############################################################################
# Makefile for building: qt-ios-app-test.app/Contents/MacOS/qt-ios-app-test
# Generated by qmake (3.0) (Qt 5.2.0)
# Project:  qt-ios-app-test.pro
# Template: app
# Command: /usr/bin/ios_qmake -spec macx-xcode -o qt-ios-app-test.xcodeproj/project.pbxproj qt-ios-app-test.pro
#############################################################################

MAKEFILE      = project.pbxproj

MOC       = /Users/chenhsueh-min/Qt5.2.0/5.2.0/ios/bin/moc
UIC       = /Users/chenhsueh-min/Qt5.2.0/5.2.0/ios/bin/uic
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DDARWIN_NO_CARBON -DQT_NO_PRINTER -DQT_NO_PRINTDIALOG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
INCPATH       = -I../../../Qt5.2.0/5.2.0/ios/mkspecs/macx-ios-clang -I. -I/Users/chenhsueh-min/Qt5.2.0/5.2.0/ios/mkspecs/macx-ios-clang/ios -I../../../Qt5.2.0/5.2.0/ios/include -I../../../Qt5.2.0/5.2.0/ios/include/QtWidgets -I../../../Qt5.2.0/5.2.0/ios/include/QtGui -I../../../Qt5.2.0/5.2.0/ios/include/QtCore -I. -I.
DEL_FILE  = rm -f
MOVE      = mv -f

IMAGES = 
PARSERS =
preprocess: $(PARSERS) compilers
clean preprocess_clean: parser_clean compiler_clean

parser_clean:
mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compilers: ./moc_mainwindow.cpp ./ui_mainwindow.h
compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: ../../../Qt5.2.0/5.2.0/ios/include/QtWidgets/QMainWindow \
		../../../Qt5.2.0/5.2.0/ios/include/QtWidgets/qmainwindow.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtWidgets/qwidget.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtGui/qwindowdefs.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qglobal.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qconfig.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qfeatures.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qsystemdetection.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qprocessordetection.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qcompilerdetection.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qglobalstatic.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qatomic.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qbasicatomic.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qatomic_bootstrap.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qgenericatomic.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qatomic_msvc.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qatomic_integrity.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qoldbasicatomic.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qatomic_vxworks.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qatomic_power.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qatomic_alpha.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qatomic_armv7.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qatomic_armv6.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qatomic_armv5.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qatomic_bfin.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qatomic_ia64.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qatomic_mips.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qatomic_s390.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qatomic_sh4a.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qatomic_sparc.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qatomic_x86.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qatomic_cxx11.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qatomic_gcc.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qatomic_unix.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qmutex.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qlogging.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qflags.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qtypeinfo.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qtypetraits.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qsysinfo.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qobjectdefs.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qnamespace.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qobjectdefs_impl.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtGui/qwindowdefs_win.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qobject.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qstring.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qchar.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qbytearray.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qrefcount.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qarraydata.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qstringbuilder.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qlist.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qalgorithms.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qiterator.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qcoreevent.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qscopedpointer.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qmetatype.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qvarlengtharray.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qcontainerfwd.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qisenum.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qobject_impl.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qmargins.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qrect.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qsize.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qpoint.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtGui/qpaintdevice.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtGui/qpalette.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtGui/qcolor.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtGui/qrgb.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qstringlist.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qdatastream.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qiodevice.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qpair.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qregexp.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qstringmatcher.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtGui/qbrush.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qvector.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtGui/qmatrix.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtGui/qpolygon.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtGui/qregion.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qline.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtGui/qtransform.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtGui/qpainterpath.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtGui/qimage.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtGui/qpixmap.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qsharedpointer.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qshareddata.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qsharedpointer_impl.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qhash.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtGui/qfont.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtGui/qfontmetrics.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtGui/qfontinfo.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtWidgets/qsizepolicy.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtGui/qcursor.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtGui/qkeysequence.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtGui/qevent.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qvariant.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qmap.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qdebug.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qtextstream.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qlocale.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qset.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qcontiguouscache.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qurl.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qurlquery.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qfile.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtCore/qfiledevice.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtGui/qvector2d.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtGui/qtouchdevice.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtWidgets/qtabwidget.h \
		../../../Qt5.2.0/5.2.0/ios/include/QtGui/qicon.h \
		mainwindow.h
	/Users/chenhsueh-min/Qt5.2.0/5.2.0/ios/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/Users/chenhsueh-min/Qt5.2.0/5.2.0/ios/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

